---
# Indirizzo del server
ServerAddress: "localhost"
# Indirizzo di multicast
MulticastAddress: "239.255.32.32"
# Porta TCP del server
TCPPort: 1080
# Porta UDP del server
UDPPort: 44444
# Host su cui si trova il registry
RegHost: "localhost"
# Porta su cui si trova il registry
RegPort: 1846
# Percentuale di punti da assegnare all'autore, il restante andrà ai curatori. Deve essere compreso tra 0 e 1.
AuthorReward: 0.75
# Intervallo fra un calcolo delle ricompense e il successivo, in secondi
PointsAwardInterval: 300
# Timeout della socket
selectTimeout: 2000